### PR TITLE
Update deps and remove unused dep.

### PR DESCRIPTION
**Pull request by vext01**

### CODE REVIEW

**Comment by vext01** [comment]
```
^ no implementation for `u32 & elf::types::ProgFlag`
```

That's odd. Because without my change to that bit of code I get:
```
error[E0610]: `u32` is a primitive type and therefore doesn't have fields
   --> src/backends/perf_pt/mod.rs:524:65
    |
524 |                 if hdr.type_() != PT_LOAD || hdr.flags() & PF_X.0 == 0 {
    |                                                                 ^
```

**Comment by vext01** [comment]
`cargo update` solved it locally.

Ready to squash?

**Comment by ptersilie** [comment]
Please do.

**Comment by vext01** [comment]
splat.

**Pull request merged**
