### PR TITLE
Fix warnings and errors

### PR DESCRIPTION
**Pull request by ptersilie**
This PR fixes some warnings and errors resulting from changes in some dependencies and rustc.

### CODE REVIEW

**Comment by vext01** [comment]
LGTM, but I think the second commit message could be expanded to explain what we've done.

**Comment by ptersilie** [comment]
Should I also squash the last commit while I'm doing that?

**Comment by vext01** [comment]
I think these make sense as separate commits in this instance.

**Comment by ptersilie** [comment]
Commit message updated.

**Pull request merged**
